---
- name: Pull docker image of Lab3Junit
  hosts: all
  vars:
    ansible_python_interpreter: /home/deepinder/anaconda3/bin/python3
  tasks:
    - name: Pull devops calculator image
      docker_image:
        name: deepguy499/spe_mini_project
        source: pull