---
- name: Pull docker image of Lab3Junit
  hosts: all
  vars:
    ansible_python_interpreter: "python"
  tasks:
    - name: Pull devops calculator image
      docker_image:
        name: deepguy499/spe_mini_project
        source: pull